* table of contents                                                     :TOC:
- [[#basic-configuration][basic configuration]]
- [[#user-interface][user interface]]
- [[#key-bindings][key bindings]]
- [[#visual][visual]]
- [[#navigation][navigation]]
- [[#editing][editing]]
- [[#programming][programming]]
- [[#operating-system][operating system]]
- [[#org-mode][org mode]]
- [[#menu-keys][menu keys]]

* basic configuration
  A bigger garbage collect threshold can make emacs boot faster,
  mostly prevent it to become a weakness.
  #+begin_src emacs-lisp
    (setq gc-cons-threshold 100000000)
  #+end_src

  Turnoff all of these things to make emacs become pretty and
  cool. Lacking of theses have none affect on a pure keyboard driven
  user.
  #+begin_src emacs-lisp
    (tool-bar-mode -1)
    (menu-bar-mode -1)
    (blink-cursor-mode -1)
    (scroll-bar-mode -1)
  #+end_src

  The initial startup screen will be replace by dashboard.
  #+begin_src emacs-lisp
    (setq inhibit-startup-screen t)
  #+end_src

  If not config this, you will get origin emacs scrolling, which is
  scroll by once time per 50 lines.
  #+begin_src emacs-lisp
    (setq scroll-margin 0
	  scroll-conservatively 100000
	  scroll-preserve-screen-position 1)
  #+end_src

  Connect emacs with X11 clipboard. Without this, it will be messy.
  #+begin_src emacs-lisp
    (setq x-select-enable-clipboard t)
  #+end_src

  Turnoff backup and auto save, which is useless after VC take over
  the job.
  #+begin_src emacs-lisp
    (setq make-backup-files nil)
    (setq auto-save-default nil)
  #+end_src

  Set the custom file path. The file is annoying if you not move it to
  somewhere.
  #+begin_src emacs-lisp
    (setq custom-file
	  (expand-file-name "custom.el" user-emacs-directory))
  #+end_src

  Now you can set it's tab or space by the cursor.
  #+begin_src emacs-lisp
    (setq x-stretch-cursor t)
  #+end_src

  Basic setups for modeline.
  #+begin_src emacs-lisp
    (line-number-mode t)
    (column-number-mode t)
    (size-indication-mode t)
  #+end_src

  Input character When selection is active to delete the selection.
  #+begin_src emacs-lisp
    (delete-selection-mode 1)
  #+end_src

  A general and basic support for pair.
  #+begin_src emacs-lisp
    (electric-pair-mode 1)
    (show-paren-mode 1)
    (setq show-paren-style 'parenthesis)
  #+end_src

  Delete trailing whitespaces when save the file.
  #+begin_src emacs-lisp
    (add-hook 'before-save-hook 'delete-trailing-whitespace)
  #+end_src

  On the fly spell checking. the flyspell-prog-mode only check
  comments and strings.
  #+begin_src emacs-lisp
    (add-hook 'text-mode-hook 'flyspell-mode)
    (add-hook 'prog-mode-hook 'flyspell-prog-mode)
  #+end_src

  Subword-mode makes moving actions obey camel case rules.
  #+begin_src emacs-lisp
    (add-hook 'java-mode-hook 'subword-mode)
    (add-hook 'go-mode-hook 'subword-mode)
  #+end_src

  Answer the exit question by one letter.
  #+begin_src emacs-lisp
    (fset 'yes-or-no-p 'y-or-n-p)
  #+end_src

  Emacs disable some features by default, you have to enable the
  disable.
  #+begin_src emacs-lisp
    (put 'downcase-region 'disabled nil)
    (put 'upcase-region 'disabled nil)
  #+end_src

  Add a path to emacs theme load path for loading my custom theme.
  #+begin_src emacs-lisp
    (add-to-list 'custom-theme-load-path
		 (expand-file-name user-emacs-directory))
  #+end_src

  Activate the winner mode. Winner mode can undo and redo the windows
  layout.
  #+begin_src emacs-lisp
    (when (fboundp 'winner-mode)
      (winner-mode 1))
  #+end_src

  Set the default font to Fira, default CJK font to Wenquanyi Zen hei.
  #+begin_src emacs-lisp
    (set-face-attribute 'default nil :font "Fira Code 11")
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font (frame-parameter nil 'font)
			charset
			(font-spec :family "WenQuanYi Zen Hei" :size 16)))
  #+end_src

  Enable package manager and install use-package.
  #+begin_src emacs-lisp
    (setq package-archives
	  '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
	    ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
	    ("emacswiki" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/emacswiki/")))

    (package-initialize)

    (unless package-archive-contents
      (package-refresh-contents))

    (unless (package-installed-p 'use-package)
      (package-install 'use-package))

    (require 'use-package)
    (setq use-package-verbose t)
    (setq use-package-always-ensure t)
  #+end_src
* user interface
  #+begin_src emacs-lisp
    (use-package swiper
      :config
      (ivy-mode 1)
      (counsel-mode 1)
      (setq ivy-use-virtual-buffers t)
      (setq enable-recursive-minibuffers t)
      (setq ivy-height 13)
      :bind (("C-s" . swiper)
	     ("M-x" . counsel-M-x)
	     ("C-x C-f" . counsel-find-file)))

    (use-package smex)

    (use-package doom-themes
      :config
      (load-theme 'doom-ayu-dark t)
      (doom-themes-org-config))

    (use-package doom-modeline
      :init (doom-modeline-mode 1))

    (use-package helpful
      :bind (("C-h f" . helpful-callable)
	     ("C-h v" . helpful-variable)
	     ("C-h k" . helpful-key)))

    (use-package which-key
      :config (which-key-mode))

    (use-package dashboard
      :config
      (setq dashboard-startup-banner (expand-file-name "banner.png" user-emacs-directory))
      (dashboard-setup-startup-hook))

    (use-package rainbow-mode :commands rainbow-mode)

    (use-package undo-tree
      :config (global-undo-tree-mode)
      :bind ("M-/" . undo-tree-redo))

    (use-package diff-hl
      :config (global-diff-hl-mode))

    (use-package eyebrowse
      :config (eyebrowse-mode t))

    (use-package volatile-highlights
      :config (volatile-highlights-mode t))

    (use-package org-bullets
      :config (setq org-bullets-bullet-list '("λ" "μ" "ν" "ξ" ))
      :hook (org-mode . (lambda () (org-bullets-mode 1))))

    (use-package info+)
  #+end_src
* key bindings
  #+begin_src emacs-lisp
    (use-package hydra)

    (use-package god-mode :bind ("<escape>" . god-loccal-mode))
  #+end_src
* visual
  #+begin_src emacs-lisp
    (use-package pangu-spacing
      :hook  (org-mode . pangu-spacing-mode))

    (use-package nameless
      :commands nameless-mode)
  #+end_src
* navigation
  #+begin_src emacs-lisp
    (use-package ace-window :commands ace-window)

    (use-package avy :commands avy-goto-char-timer)

    (use-package ace-link :config (ace-link-setup-default))

    (use-package goto-line-preview
      :config
      (global-set-key [remap goto-line] 'goto-line-preview))
  #+end_src
* editing
  #+begin_src emacs-lisp
    (use-package multiple-cursors
      :bind (("C->" . mc/mark-next-like-this)
	     ("C-<" . mc/mark-previous-like-this)))

    (use-package expand-region
      :bind ("C-=" . er/expand-region))

    (use-package move-text
      :bind
      (("M-p" . move-text-up)
       ("M-n" . move-text-down)))

    (use-package wgrep :defer t)
  #+end_src
* programming
  #+begin_src emacs-lisp
    (use-package projectile
      :config
      (projectile-mode +1)
      (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))

    (use-package counsel-projectile
      :config
      (counsel-projectile-mode 1))

    (use-package hl-todo :hook (prog-mode . hl-todo-mode))

    (use-package company
      :config
      (add-hook 'after-init-hook 'global-company-mode)
      (setq company-idle-delay 0)
      (setq company-minimum-prefix-length 1))

    (use-package yasnippet
      :hook
      (after-init . yas-global-mode))

    (use-package yasnippet-snippets
      :after yasnippet)

    (use-package auto-yasnippet
      :bind (("C-c [" . aya-create)
	     ("C-c ]" . aya-expand)))

    (use-package eglot :commands eglot)

    (use-package flycheck
      :hook (after-init . global-flycheck-mode))

    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))

    (use-package highlight-numbers
      :hook (prog-mode . highlight-numbers-mode))

    (use-package lispy
      :hook
      (emacs-lisp-mode . lispy-mode)
      (lisp-mode . lispy-mode))

    (use-package magit
      :bind ("C-x g" . magit))

    (use-package forge
      :after magit)

    (use-package git-timemachine
      :commands git-timemachine)

    (use-package git-messenger
      :commands git-messenger:popup-message)

    (use-package gitconfig-mode)

    (use-package gitattributes-mode)

    (use-package gitignore-mode)

    (use-package sly :commands sly
      :config (setq inferior-lisp-program "/usr/bin/sbcl"))

    (use-package geiser :commands geiser)

    (use-package web-mode :mode "\\.html\\'")

    (use-package emmet-mode :hook (web-mode . emmet-mode))

    (use-package skewer-mode :commands run-skewer
      :hook ((js2-mode . skewer-mode)
	     (css-mode . skewer-css-mode )
	     (html-mode . skewer-html-mode)))

    (use-package haskell-mode :mode "\\.hs\\'")

    (use-package go-mode :mode "\\.go\\'")

    (use-package rust-mode :mode "\\.rs\\'")

    (use-package php-mode :mode "\\.php\\'")

    (use-package lua-mode :mode "\\.lua\\'")

    (use-package json-mode :mode "\\.json\\'")

    (use-package markdown-mode :mode "\\.md\\'")
  #+end_src
* operating system
  #+begin_src emacs-lisp
    (use-package mingus :commands mingus)

    (use-package rime
      :custom
      (default-input-method "rime"))

    (use-package esh-autosuggest
      :hook (eshell-mode . esh-autosuggest-mode))

    (use-package restart-emacs
      :commands restart-emacs)

    (use-package google-this
      :config
      (google-this-mode 1))

    (use-package pdf-tools
      :config
      (pdf-tools-install))

    (use-package tex
      :defer t
      :ensure auctex
      :config
      (setq TeX-auto-save t))

    (use-package esup
      :commands esup)

    (use-package cal-china-x
      :config
      (setq mark-holidays-in-calendar t)
      (setq cal-china-x-important-holidays cal-china-x-chinese-holidays)
      (setq cal-china-x-general-holidays '((holiday-lunar 1 15 "元宵节")))
      (setq calendar-holidays
	    (append cal-china-x-important-holidays
		    cal-china-x-general-holidays
		    holiday-other-holidays)))

    (use-package nov-mode
      :ensure nov
      :mode "\\.epub\\'")
  #+end_src
* org mode
  #+begin_src emacs-lisp
    (use-package toc-org
      :config
      (if (require 'toc-org nil t)
	(add-hook 'org-mode-hook 'toc-org-mode)))
  #+end_src
* menu keys
  The menu key is very useful. I bind it with so many commands, which
  are very frequently used.
  #+begin_src emacs-lisp
    (define-prefix-command 'menu-key-map)
    (define-key menu-key-map (kbd "h") 'beginning-of-buffer)
    (define-key menu-key-map (kbd "n") 'end-of-buffer)
    (define-key menu-key-map (kbd "o") 'mode-line-other-buffer)
    (define-key menu-key-map (kbd "f") 'switch-to-buffer)
    (define-key menu-key-map (kbd ";") 'save-buffer)
    (define-key menu-key-map (kbd "k") 'kill-buffer)
    (define-key menu-key-map (kbd "b") 'mark-whole-buffer)
    (define-key menu-key-map (kbd "w") 'ace-window)
    (define-key menu-key-map (kbd "e") 'counsel-find-file)
    (define-key menu-key-map (kbd "r") 'counsel-recentf)
    (define-key menu-key-map (kbd "a") 'counsel-ag)
    (define-key menu-key-map (kbd "0") 'delete-window)
    (define-key menu-key-map (kbd "1") 'delete-other-windows)
    (define-key menu-key-map (kbd "2") 'split-window-below)
    (define-key menu-key-map (kbd "3") 'split-window-right)
    (define-key menu-key-map (kbd "8") 'org-edit-special)
    (define-key menu-key-map (kbd "9") 'org-edit-src-exit)
    (define-key menu-key-map (kbd "[") 'winner-undo)
    (define-key menu-key-map (kbd "]") 'winner-redo)
    (define-key menu-key-map (kbd "m") 'counsel-bookmark)
    (define-key menu-key-map (kbd "s") 'flyspell-auto-correct-word)
    (define-key menu-key-map (kbd "j") 'avy-goto-char-timer)
    (define-key menu-key-map (kbd "<menu>") 'counsel-M-x)
    (define-key menu-key-map (kbd "SPC") 'magit)
    (define-key menu-key-map (kbd "p") 'projectile-command-map)
    (global-set-key (kbd "<menu>") 'menu-key-map)
  #+end_src
